# Generated by Django 5.2 on 2025-09-29 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BWLapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='cost_price',
        ),
    ]
