# Generated by Django 5.2 on 2025-08-12 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BWLapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='quantity_in_stock',
            new_name='quantity',
        ),
    ]
