# Generated by Django 5.2.5 on 2025-10-01 07:37

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('BWLapp', '0002_remove_product_cost_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(
                upload_to='product_images/',
                blank=True,
                null=True,
                help_text='Upload a high-quality product image.',
            ),
        ),
    ]
