# Generated by Django 5.2 on 2025-08-19 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BWLapp', '0002_rename_quantity_in_stock_product_quantity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='amount',
            new_name='total_amount',
        ),
    ]
