# Generated by Django 5.2 on 2025-08-25 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BWLapp', '0006_employee_alter_customuser_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='stock_quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
