# Generated by Django 5.2 on 2025-08-25 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BWLapp', '0007_product_stock_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='quantity',
        ),
    ]
