# Generated by Django 5.2 on 2025-09-04 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BWLapp', '0009_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='bio',
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(default='BWLapp/images/profile.jpg', upload_to='profile_pics/'),
        ),
    ]
