# Generated by Django 5.2 on 2025-09-04 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BWLapp', '0010_remove_profile_bio_alter_profile_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(default='BWLapp/profile.jpg', upload_to='profile_pics/'),
        ),
    ]
