# Generated by Django 5.2 on 2025-09-04 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BWLapp', '0011_alter_profile_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
