# Generated by Django 5.2 on 2025-09-06 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BWLapp', '0013_category_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='low_stock_threshold',
            field=models.PositiveIntegerField(default=10),
        ),
    ]
