# Generated by Django 5.2 on 2025-09-07 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BWLapp', '0014_product_low_stock_threshold'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='cost_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
