# Generated by Django 5.2 on 2025-09-17 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BWLapp', '0015_product_cost_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='packaging',
            field=models.CharField(choices=[('6pack', '6 pack'), ('dozen', 'dozen'), ('carton', 'carton'), ('bulk', 'bulk')], default='6pack', max_length=20),
        ),
    ]
