# Generated by Django 5.2.5 on 2025-09-22 12:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BWLapp', '0017_notification_audittrail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='is_available',
        ),
        migrations.RemoveField(
            model_name='product',
            name='low_stock_threshold',
        ),
        migrations.RemoveField(
            model_name='product',
            name='packaging',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='stock_quantity',
        ),
        migrations.AlterField(
            model_name='product',
            name='cost_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_type', models.CharField(choices=[('6pack', '6-Pack'), ('dozen', 'Dozen'), ('24pack', '24-Pack'), ('bulk', 'Bulk')], help_text="e.g., '6-Pack', 'Dozen'", max_length=50)),
                ('quantity', models.PositiveIntegerField(default=0, help_text='Number of packages in stock')),
                ('price_per_package', models.DecimalField(decimal_places=2, help_text='Price for this specific package type', max_digits=10)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_items', to='BWLapp.product')),
            ],
        ),
    ]
