# Generated by Django 5.2 on 2025-09-23 04:01

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BWLapp', '0018_remove_product_is_available_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='selling_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='stock',
            name='package_type',
            field=models.CharField(choices=[('6pack', '6-Pack'), ('dozen', 'Dozen'), ('Carton', 'Carton'), ('bulk', 'Bulk')], help_text="e.g., '6-Pack', 'Dozen'", max_length=50),
        ),
    ]
