# Generated by Django 5.2 on 2025-09-23 09:20

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BWLapp', '0019_product_selling_price_alter_stock_package_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='cost_per_package',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Cost for this specific package type', max_digits=10),
        ),
    ]
