# Generated by Django 5.2 on 2025-09-24 01:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BWLapp', '0020_stock_cost_per_package'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='cost_per_package',
        ),
    ]
